### ISSUE TITLE
Muammo

### ISSUE THREAD

**Issue by ismailovquvonchbek** [soln1shkame/chopmadim_imtihon#1]
https://github.com/soln1shkame/chopmadim_imtihon/blob/89dd8599fcf87f297d2bdec819e663baf494aeaf/index.html#L92

**Comment by ismailovquvonchbek** [comment]
Main bir marta ochiladi har bitta section uchun emas shu joyida adashgansiz togirlab qoyishni maslahat beraman.

**Comment by soln1shkame** [comment]
men ozi wunday qlaman

**Comment by ismailovquvonchbek** [comment]
Zorsan ezasan

**Comment by ismailovquvonchbek** [comment]
Lekin unday qilinmaydi qizi

**Comment by soln1shkame** [comment]
menga farqi yogee
